# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "599a86c67f2faee4410595ceb1a5762b"
name = "MomoGate"
application_url = "https://momo-gate-one.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

[access_scopes]
scopes = "write_products,read_orders,write_orders,read_customers"

[auth]
redirect_urls = [
  "https://momo-gate-one.vercel.app/auth/callback",
  "https://momo-gate-one.vercel.app/auth/shopify/callback",
  "https://momo-gate-one.vercel.app/api/auth"
]
