api_version = "2025-10"
uid = "91f8c9a5-8e7f-3381-7665-ae10b0dc637000cd7ac5"

[[extensions]]
type = "ui_extension"
name = "Paiement Mobile Money"
handle = "checkout-payment"

  # Page de confirmation de commande (thank you page)
  [[extensions.targeting]]
  module = "./src/index.ts"
  target = "purchase.thank-you.block.render"
  export = "default"
